const ORDER_STATUS = {
    CREATED: "CREATED",
    SEARCHING_DRIVER: "SEARCHING_DRIVER",
    ASSIGNED: "ASSIGNED",
    PICKED_UP: "PICKED_UP",
    IN_TRANSIT: "IN_TRANSIT",
    DELIVERED: "DELIVERED",
    CANCELLED: "CANCELLED",
};

const ORDER_PRIORITY = {
    LOW: "LOW",
    NORMAL: "NORMAL",
    HIGH: "HIGH",
    URGENT: "URGENT",
};

module.exports = {
    ORDER_STATUS,
    ORDER_PRIORITY,
};